# Generated by Django 3.2 on 2022-04-04 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='alltime_leaderboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abbr', models.CharField(max_length=4, unique=True)),
                ('first_name', models.CharField(max_length=32)),
                ('last_name', models.CharField(max_length=32)),
                ('driver_no', models.IntegerField()),
                ('races', models.IntegerField()),
                ('points', models.IntegerField()),
                ('wins', models.IntegerField()),
                ('podiums', models.IntegerField()),
                ('poles', models.IntegerField()),
                ('most_zeros', models.IntegerField()),
                ('seasons', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='current_leaderboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abbr', models.CharField(max_length=4, unique=True)),
                ('first_name', models.CharField(max_length=32)),
                ('last_name', models.CharField(max_length=32)),
                ('driver_no', models.IntegerField()),
                ('team_name', models.CharField(max_length=64)),
                ('team_color', models.CharField(max_length=7)),
                ('points', models.FloatField()),
                ('rank_override', models.IntegerField()),
            ],
        ),
    ]
