# Generated by Django 3.2 on 2022-05-17 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('input_portal', '0005_results_data_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='results_racecodes',
            name='sprint',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='results_data',
            name='score',
            field=models.IntegerField(),
        ),
    ]
