# Generated by Django 3.2 on 2022-05-17 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('input_portal', '0006_auto_20220517_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='results_data',
            name='grid',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='sprint_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pos', models.IntegerField()),
                ('estimator', models.CharField(max_length=4)),
                ('team_color', models.CharField(max_length=7)),
                ('grid', models.IntegerField()),
                ('score', models.IntegerField()),
                ('pts', models.FloatField()),
                ('racecode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='input_portal.results_racecodes')),
            ],
        ),
    ]
