# Generated by Django 3.2 on 2022-05-17 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('input_portal', '0008_auto_20220517_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alltime_leaderboard',
            name='points',
            field=models.FloatField(),
        ),
    ]
