# Generated by Django 3.2 on 2022-05-17 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('input_portal', '0010_auto_20220517_2113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alltime_leaderboard',
            name='sprint_king',
        ),
        migrations.RemoveField(
            model_name='alltime_leaderboard',
            name='sprint_medals',
        ),
        migrations.RemoveField(
            model_name='alltime_leaderboard',
            name='sprints',
        ),
    ]
