# Generated by Django 3.2 on 2022-05-17 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('input_portal', '0012_auto_20220517_2115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alltime_leaderboard',
            name='sprint_king',
        ),
        migrations.RemoveField(
            model_name='alltime_leaderboard',
            name='sprint_medals',
        ),
        migrations.RemoveField(
            model_name='alltime_leaderboard',
            name='sprints',
        ),
    ]
